DROP TABLE IF EXISTS products,discount_card;

CREATE TABLE IF NOT EXISTS products
(
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name  VARCHAR(100),
    product_price FLOAT4,
    product_discount boolean,
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
);
CREATE TABLE IF NOT EXISTS discount_card
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_card BIGINT,
    discount_percent INT,
    CONSTRAINT discount_card_pkey PRIMARY KEY (id)
);
