DROP TABLE IF EXISTS products,discount_card;

CREATE TABLE IF NOT EXISTS products
(
    id_product    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_product  VARCHAR(100),
    price_product FLOAT4,
    discount_product boolean,
    CONSTRAINT product_pkey PRIMARY KEY (id_product)
);
CREATE TABLE IF NOT EXISTS discount_card
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_card BIGINT,
    discount_percent INT,
    CONSTRAINT discount_card_pkey PRIMARY KEY (id)
);
